# Generated by Django 5.2 on 2026-08-13 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='Brief description for listing pages', max_length=200)),
                ('detailed_description', models.TextField(help_text='Full service description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Service price in local currency', max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Service duration in minutes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('coming_soon', 'Coming Soon')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='services/images/')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title (max 60 chars)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO Description (max 160 chars)', max_length=160)),
                ('requirements', models.TextField(blank=True, help_text='Special requirements or prerequisites')),
                ('what_to_expect', models.TextField(blank=True, help_text='What patients should expect during the service')),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
                'indexes': [models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'), models.Index(fields=['status'], name='services_se_status_288ecc_idx'), models.Index(fields=['category'], name='services_se_categor_7ca2f8_idx')],
            },
        ),
    ]
