# Generated by Django 5.2 on 2026-08-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('appointment', 'Appointment Request'), ('billing', 'Billing Question'), ('medical', 'Medical Information'), ('feedback', 'Feedback'), ('complaint', 'Complaint'), ('other', 'Other')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('privacy_consent', models.BooleanField(default=False, help_text='User consented to privacy policy')),
                ('data_processing_consent', models.BooleanField(default=False, help_text='User consented to data processing')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for security tracking', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent for security tracking')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='contact_con_status_fa3e24_idx'), models.Index(fields=['inquiry_type'], name='contact_con_inquiry_9ff3d4_idx'), models.Index(fields=['created_at'], name='contact_con_created_fddb83_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_consent', models.BooleanField(default=False, help_text='User consented to privacy policy')),
                ('marketing_consent', models.BooleanField(default=False, help_text='User consented to marketing communications')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for security tracking', null=True)),
                ('receive_updates', models.BooleanField(default=True)),
                ('receive_promotions', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='contact_new_email_775f71_idx'), models.Index(fields=['is_active'], name='contact_new_is_acti_9e4a66_idx')],
            },
        ),
    ]
