# Generated by Django 5.2 on 2026-08-18 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(help_text='Insurance provider company name', max_length=200)),
                ('policy_number', models.CharField(help_text='Insurance policy number', max_length=100, unique=True)),
                ('mental_health_coverage_details', models.TextField(blank=True, help_text='Details of mental health coverage, sessions covered, etc.')),
                ('copay_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Copay amount per session', max_digits=10)),
                ('expiry_date', models.DateField(help_text='Insurance policy expiry date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the insurance is currently active')),
                ('is_deleted', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'expiry_date'],
                'indexes': [models.Index(fields=['patient', 'is_active'], name='patients_in_patient_3a3a18_idx'), models.Index(fields=['is_deleted'], name='patients_in_is_dele_a88b92_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_name', models.CharField(help_text='e.g., Major Anxiety Disorder, PTSD, Depression, Bipolar Disorder', max_length=200)),
                ('diagnosis_date', models.DateField(help_text='Date when condition was diagnosed')),
                ('therapy_history', models.TextField(blank=True, help_text='Previous therapy treatments and their outcomes')),
                ('current_medications', models.TextField(blank=True, help_text='Current psychiatric medications and dosages')),
                ('notes', models.TextField(blank=True, help_text='Additional clinical notes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_treatment', 'In Treatment'), ('in_remission', 'In Remission'), ('resolved', 'Resolved'), ('chronic', 'Chronic')], default='active', help_text='Current status of the condition', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-diagnosis_date', 'condition_name'],
                'indexes': [models.Index(fields=['patient', 'status'], name='patients_me_patient_c3e545_idx'), models.Index(fields=['is_deleted'], name='patients_me_is_dele_822aaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_name', models.CharField(help_text='Name of the doctor or therapist', max_length=200)),
                ('visit_date', models.DateTimeField(help_text='Date and time of the visit')),
                ('mental_health_diagnosis', models.TextField(blank=True, help_text='Primary mental health diagnosis or assessment')),
                ('therapy_notes', models.TextField(blank=True, help_text='Detailed therapy session notes and observations')),
                ('prescription_details', models.TextField(blank=True, help_text='Medications prescribed with dosages')),
                ('recommended_treatment_plan', models.TextField(blank=True, help_text='Recommended treatment plan and next steps')),
                ('is_deleted', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
                'indexes': [models.Index(fields=['patient', 'visit_date'], name='patients_me_patient_fed24a_idx'), models.Index(fields=['is_deleted'], name='patients_me_is_dele_2aac60_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_title', models.CharField(help_text='Title or description of the document', max_length=200)),
                ('document_type', models.CharField(choices=[('psychological_assessment', 'Psychological Assessment'), ('lab_report', 'Lab Report'), ('psychiatric_evaluation', 'Psychiatric Evaluation'), ('self_report_scale', 'Self-Report Scale'), ('therapy_notes', 'Therapy Notes'), ('insurance_document', 'Insurance Document'), ('other', 'Other')], help_text='Type of document', max_length=50)),
                ('file', models.FileField(help_text='Upload the document file', upload_to='patient_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Date when document was uploaded')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the document')),
                ('is_deleted', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['patient', 'document_type'], name='patients_pa_patient_377653_idx'), models.Index(fields=['is_deleted'], name='patients_pa_is_dele_a903d6_idx')],
            },
        ),
    ]
